//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW8
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageHistory
    {
        public string Message { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public int MId { get; set; }
    }
}
